# Generated by Django 2.2.6 on 2019-10-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='создана')),
                ('terminated', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'keyboard'), (2, 'mouse button')], verbose_name='тип события')),
                ('registered', models.DateTimeField(db_index=True, help_text='серверное время', verbose_name='зарегистрировано')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.Play', verbose_name='запись')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
    ]
