# Generated by Django 2.2.6 on 2019-10-14 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191014_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='серверное время', verbose_name='зарегистрировано'),
        ),
        migrations.AlterField(
            model_name='play',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='создана'),
        ),
    ]
