# Generated by Django 2.2.6 on 2019-10-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20191014_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kind',
        ),
    ]
